import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,Users,MessageSquare,CalendarDays,Clock3,ClipboardCheck,FileText,Bell,Search,Menu,Plus,CheckCircle2,ChevronRight,Building2,Settings,Sun,Moon,X,LogOut,Check}from'lucide-react';
import'./styles.css';
const nav=[['Overview',LayoutDashboard],['People',Users],['Messages',MessageSquare],['Calendar',CalendarDays],['Attendance',Clock3],['Tasks',ClipboardCheck],['Files',FileText],['Approvals',CheckCircle2]];
const initialTasks=[['Finalize Q4 report','Due today','high'],['Review leave request','Due today','medium'],['Update project brief','Tomorrow','low'],['Send weekly update','Fri, Oct 3','low']];
function App(){const[page,setPage]=useState('Overview'),[open,setOpen]=useState(true),[dark,setDark]=useState(false),[search,setSearch]=useState(''),[notice,setNotice]=useState(false),[settings,setSettings]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[tasks,setTasks]=useState(initialTasks),[newItem,setNewItem]=useState('');
const flash=m=>{setToast(m);setTimeout(()=>setToast(''),2200)},go=p=>{setPage(p);setNotice(false);setSettings(false)},action=n=>{setModal(n);setNewItem('')},submit=()=>{if(!newItem.trim())return flash('Please enter a name');flash(modal+' created successfully');setModal(null)},complete=n=>{setTasks(t=>t.filter(x=>x[0]!==n));flash('Task marked complete')};
const filteredTasks=useMemo(()=>tasks.filter(x=>x.join(' ').toLowerCase().includes(search.toLowerCase())),[tasks,search]);
return <div className={dark?'app dark':'app'}><aside className={open?'sidebar':'sidebar collapsed'}><div className="brand"><div className="brandmark"><Users size={22}/></div>{open&&<div><b>Co-workers</b><span>Work better together</span></div>}</div><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>go(n)} key={n}><I size={19}/>{open&&<span>{n}</span>}</button>)}</nav>{open&&<button className="workspace" onClick={()=>flash('Organization selector opened')}><Building2 size={18}/><div><b>My Organization</b><span>Head Office</span></div><ChevronRight size={15}/></button>}<button className="settings" onClick={()=>setSettings(true)}><Settings size={18}/>{open&&'Settings'}</button></aside>
<main><header><button className="icon" onClick={()=>setOpen(!open)}><Menu/></button><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people, messages, files..."/>{search&&<button className="clear" onClick={()=>setSearch('')}><X size={15}/></button>}</div><div className="header-actions"><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="icon notification" onClick={()=>setNotice(!notice)}><Bell/><i/></button><button className="avatar" onClick={()=>flash('Profile menu opened')}>AS</button></div>{notice&&<div className="popover"><b>Notifications</b><p>New leave request from Ada</p><p>Project review starts at 10:30</p><button className="ghost" onClick={()=>{setNotice(false);flash('Notifications marked as read')}}>Mark as read</button></div>}</header>
<section className="content"><div className="topline"><div><p className="eyebrow">WORKSPACE</p><h1>{page}</h1><p className="muted">Welcome back, Stephen. Here’s what’s happening across your workplace.</p></div><button className="primary" onClick={()=>action(page==='People'?'Staff member':page==='Calendar'?'Meeting':page==='Tasks'?'Task':page==='Files'?'Document':'Request')}><Plus size={18}/> Create</button></div>
{page==='Overview'?<Overview filteredTasks={filteredTasks} complete={complete} action={action} go={go}/>:<Module page={page} action={action} search={search} flash={flash}/>}</section></main>
{settings&&<Modal title="Settings" close={()=>setSettings(false)}><div className="settings-list"><button onClick={()=>{setDark(!dark);flash('Theme updated')}}><Sun size={18}/> Toggle dark mode</button><button onClick={()=>flash('Account settings opened')}><Users size={18}/> Account settings</button><button onClick={()=>flash('Security settings opened')}><CheckCircle2 size={18}/> Security</button><button onClick={()=>flash('You are already signed in')}><LogOut size={18}/> Sign out</button></div></Modal>}
{modal&&<Modal title={'Create '+modal} close={()=>setModal(null)}><input className="modalinput" autoFocus value={newItem} onChange={e=>setNewItem(e.target.value)} placeholder={'Enter '+modal.toLowerCase()+' name...'}/><button className="primary full" onClick={submit}><Check size={18}/> Create</button></Modal>}
{toast&&<div className="toast">{toast}</div>}</div>}
function Overview({filteredTasks,complete,action,go}){return <><div className="stats">{[['Team members','128','+8 this month',Users,'People'],['Open tasks','24','6 due today',ClipboardCheck,'Tasks'],['Today’s meetings','7','Next at 10:30',CalendarDays,'Calendar'],['Pending approvals','12','4 urgent',CheckCircle2,'Approvals']].map(([a,b,c,I,p])=><button className="card stat" onClick={()=>go(p)} key={a}><div className="staticon"><I size={20}/></div><div><span>{a}</span><strong>{b}</strong><small>{c}</small></div><ChevronRight size={16}/></button>)}</div>
<div className="grid"><div className="card panel"><div className="panelhead"><div><h2>Today</h2><p>Thursday, October 2</p></div><button className="ghost" onClick={()=>go('Calendar')}>View calendar</button></div>{[['09:00','Team stand-up','Product · 8 attendees'],['10:30','Project review','Engineering · 6 attendees'],['13:00','Department meeting','Operations · 12 attendees'],['15:30','Client call','Sales · 4 attendees']].map(x=><button className="event" onClick={()=>action('Meeting details')} key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><span>{x[2]}</span></div><ChevronRight size={17}/></button>)}</div>
<div className="card panel"><div className="panelhead"><div><h2>My tasks</h2><p>Priorities for today</p></div><button className="ghost" onClick={()=>go('Tasks')}>See all</button></div>{filteredTasks.map(x=><div className="task" key={x[0]}><span className={'dot '+x[2]}></span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><button className="check" onClick={()=>complete(x[0])}>✓</button></div>)}{!filteredTasks.length&&<p className="emptyline">No matching tasks.</p>}</div></div>
<div className="card panel"><div className="panelhead"><div><h2>Quick actions</h2><p>Common workplace actions</p></div></div><div className="quick">{[['Message a colleague',MessageSquare,'Messages'],['Schedule meeting',CalendarDays,'Calendar'],['Request leave',Clock3,'Request'],['Upload document',FileText,'Files']].map(([x,I,a])=><button onClick={()=>action(a)} key={x}><I size={19}/><span>{x}</span><ChevronRight size={15}/></button>)}</div></div></>}
function Module({page,action,search,flash}){const icons={People:Users,Messages:MessageSquare,Calendar:CalendarDays,Attendance:Clock3,Tasks:ClipboardCheck,Files:FileText,Approvals:CheckCircle2},I=icons[page]||Users;const data={People:['Staff directory','Manage employee profiles, departments and roles.'],Messages:['Team communication','Start one-to-one or group conversations.'],Calendar:['Work calendar','Meetings, events and schedules.'],Attendance:['Attendance','Clock in, clock out and review attendance.'],Tasks:['Tasks','Create, assign and track workplace tasks.'],Files:['Documents','Organize and share workplace files.'],Approvals:['Approvals','Review leave and other requests.']}[page];return <div className="module"><div className="modulehero"><div className="emptyicon"><I size={28}/></div><h2>{data[0]}</h2><p>{data[1]}</p><div className="moduleactions"><button className="primary" onClick={()=>action(page==='People'?'Staff member':page==='Calendar'?'Meeting':page==='Tasks'?'Task':page==='Files'?'Document':page==='Messages'?'Message':'Request')}><Plus size={18}/> Add new</button><button className="ghost" onClick={()=>flash(page+' refreshed')}>Refresh</button></div></div><div className="card data-preview"><b>{search?'Search results for "'+search+'"':'Ready for live data'}</b><p>Connect Supabase to load real {page.toLowerCase()} records here.</p></div></div>}
function Modal({title,close,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalhead"><h2>{title}</h2><button className="icon" onClick={close}><X/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);